"""
Backend Main Module.

This module sets up the FastAPI application, database connections, Authentication using JWT and Bcrypt,
and an asynchronous WebSocket manager to handle real-time connection from agent endpoints.
"""
import os
import json
import random
import smtplib
import logging
from email.message import EmailMessage
from contextlib import asynccontextmanager
from typing import List, Optional, Dict, Any
from datetime import datetime

from fastapi import FastAPI, Request, WebSocket, WebSocketDisconnect, Depends, HTTPException, status, BackgroundTasks
from fastapi.middleware.cors import CORSMiddleware
from fastapi.templating import Jinja2Templates
from fastapi.staticfiles import StaticFiles
from fastapi.responses import FileResponse
from pydantic import BaseModel
from jose import jwt, JWTError
from sqlmodel import Session, create_engine, SQLModel, select

# Local module imports
from src.backend.models import User, Device, SortingRule, FileEvent
from src.backend.core.security import verify_password, get_password_hash, create_access_token
from src.backend.core.config import settings
from src.backend.api.v1 import stats as stats_router

# Setup Logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Setup Jinja2 Templates
TEMPLATES_DIR = os.path.join(os.path.dirname(__file__), "templates")
templates = Jinja2Templates(directory=TEMPLATES_DIR)

# 1. DATABASE CONFIGURATION
# Database URL is acquired from the .env file generated by the launcher script
DATABASE_URL = settings.DATABASE_URL or "sqlite:///./enterprise.db"

# SQLite-specific kwargs required for multi-threading support
connect_args = {"check_same_thread": False} if "sqlite" in DATABASE_URL else {}
engine = create_engine(DATABASE_URL, connect_args=connect_args)

# 2. APPLICATION LIFECYCLE (Table Initialization)
@asynccontextmanager
async def lifespan(app: FastAPI):
    # Initializes all missing schema tables on application startup
    SQLModel.metadata.create_all(engine)
    yield

app = FastAPI(
    title="File Sorter Enterprise API",
    version="1.0.0",
    lifespan=lifespan
)

# Global CORS Policy (Required for future Desktop/Web Frontend integrations)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

# Serve Web Landing Page
app.mount("/assets", StaticFiles(directory=os.path.join(os.path.dirname(__file__), "../../../landing/assets")), name="assets")

@app.get("/")
def serve_index():
    path = os.path.join(os.path.dirname(__file__), "../../../landing/index.html")
    return FileResponse(path)

# Include stats + dashboard WebSocket router (landing page integration)
app.include_router(stats_router.router)

# FastAPI Dependency Yielding active DB sessions
def get_db():
    with Session(engine) as session:
        yield session

# 3. WEBSOCKET CONNECTION MANAGER (For Real-Time telemetry)
class ConnectionManager:
    def __init__(self):
        self.active_agents: dict[str, WebSocket] = {}

    async def connect(self, device_id: str, websocket: WebSocket):
        await websocket.accept()
        self.active_agents[device_id] = websocket
        print(f"📡 Agent connected: {device_id}")

    def disconnect(self, device_id: str):
        if device_id in self.active_agents:
            del self.active_agents[device_id]
            print(f"❌ Agent disconnected: {device_id}")

    async def broadcast_to_dashboard(self, message: dict):
        # Relay live file events to all connected web dashboard clients
        await stats_router.dashboard_manager.broadcast(message)

manager = ConnectionManager()

# 4. AUTHENTICATION ENDPOINTS
@app.post("/auth/register", status_code=status.HTTP_201_CREATED)
def register(user_data: User, db: Session = Depends(get_db)) -> dict:
    """
    Registers a new User generating Bcrypt hashes.
    
    Parameters:
        user_data (User): The user payload schema containing email and plain password.
        db (Session): Scalable database dependency injection context.
        
    Returns:
        dict: Confirmation entity harboring user creation string and integer unique ID.
        
    Raises:
        HTTPException (400): If the submitted email address is already bound to another profile.
        
    Example:
        >>> POST /auth/register {"email": "hello@world.com", "hashed_password": "123"}
        {"message": "User successfully created", "id": 1}
    """
    # Validate unique email
    existing = db.exec(select(User).where(User.email == user_data.email)).first()
    if existing:
        raise HTTPException(status_code=400, detail="Email is already registered")
    
    user_data.hashed_password = get_password_hash(user_data.hashed_password)
    db.add(user_data)
    db.commit()
    db.refresh(user_data)
    return {"message": "User successfully created", "id": user_data.id}

def send_verification_email(to_email: str, code: str, is_recovery: bool = False):
    if not settings.SMTP_USER or not settings.SMTP_PASSWORD:
        print(f"⚠️ SMTP not configured in .env. The code for {to_email} is: {code}")
        return
        
    now = datetime.now()
    date_str = now.strftime("%d-%m-%Y")
    
    if is_recovery:
        subject = f"Password reset {date_str}"
        title = "Password Recovery"
        message_body = "You requested a password reset. Use the following 6-digit code. If you didn't request this, ignore this security message."
    else:
        subject = "Verification Code - File Sorter"
        title = "Logging In"
        message_body = "A login attempt was detected. Use the following 6-digit code to securely access your account."

    template = templates.get_template("email_verification.html")
    html_content = template.render({"title": title, "message_body": message_body, "code": code})

    try:
        msg = EmailMessage()
        msg['Subject'] = subject
        msg['From'] = settings.SMTP_USER
        msg['To'] = to_email
        msg.set_content(f"Your code is: {code}. Please activate HTML view to see this message.")
        msg.add_alternative(html_content, subtype='html')

        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls()
        server.login(settings.SMTP_USER, settings.SMTP_PASSWORD)
        server.send_message(msg)
        server.quit()
        logger.info(f"Verification HTML email successfully sent to {to_email}")
    except Exception as e:
        logger.error(f"Error sending SMTP email to {to_email}: {e}")

@app.post("/auth/token")
def login(user_credentials: User, background_tasks: BackgroundTasks, db: Session = Depends(get_db)) -> dict:
    """
    Evaluates hashed authentication signatures and triggers a 2FA Verification via SMTP.
    
    Parameters:
        user_credentials (User): The user payload schema containing plain login attributes.
        background_tasks (BackgroundTasks): Native FastAPI asynchronous thread orchestrator for Email sending.
        db (Session): Scalable database dependency injection context.
        
    Returns:
        dict: Standardized API Object informing the front-end that MFA stands active.
        
    Raises:
        HTTPException (401): If plain credentials violate Bcrypt hashes checks.
        
    Example:
        >>> POST /auth/token {"email": "hello@world.com", "hashed_password": "123"}
        {"status": "pending_verification", "message": "Verification code sent to email"}
    """
    user = db.exec(select(User).where(User.email == user_credentials.email)).first()
    if not user:
        raise HTTPException(status_code=401, detail="Invalid credentials")
    
    if user.failed_login_attempts >= 3:
        code = str(random.randint(100000, 999999))
        user.verification_code = code
        db.commit()
        background_tasks.add_task(send_verification_email, user.email, code, True)
        return {"status": "requires_reset", "message": "You have exceeded login attempts. Check your email to recover your account."}
        
    if not verify_password(user_credentials.hashed_password, user.hashed_password):
        user.failed_login_attempts += 1
        db.commit()
        raise HTTPException(status_code=401, detail="Invalid credentials")
    
    code = str(random.randint(100000, 999999))
    user.verification_code = code
    user.failed_login_attempts = 0
    db.commit()
    background_tasks.add_task(send_verification_email, user.email, code, False)
    
    return {"status": "pending_verification", "message": "Verification code sent to email"}

class VerifyRequest(SQLModel):
    email: str
    code: str

@app.post("/auth/verify")
def verify_code(req: VerifyRequest, db: Session = Depends(get_db)):
    user = db.exec(select(User).where(User.email == req.email)).first()
    if not user or user.verification_code != req.code:
        raise HTTPException(status_code=401, detail="Invalid code")
    
    user.verification_code = None
    user.failed_login_attempts = 0
    db.commit()
    
    access_token = create_access_token(subject=user.email)
    return {"access_token": access_token, "token_type": "bearer"}

class ForgotPasswordRequest(SQLModel):
    email: str

@app.post("/auth/forgot-password")
def forgot_password(req: ForgotPasswordRequest, background_tasks: BackgroundTasks, db: Session = Depends(get_db)):
    user = db.exec(select(User).where(User.email == req.email)).first()
    if user:
        code = str(random.randint(100000, 999999))
        user.verification_code = code
        db.commit()
        background_tasks.add_task(send_verification_email, user.email, code, True)
    return {"message": "If the email is correct, we have sent a recovery code."}

class ResetPasswordRequest(SQLModel):
    email: str
    code: str
    new_password: str

@app.post("/auth/reset-password")
def reset_password(req: ResetPasswordRequest, db: Session = Depends(get_db)):
    user = db.exec(select(User).where(User.email == req.email)).first()
    if not user or user.verification_code != req.code:
        raise HTTPException(status_code=401, detail="Invalid or expired code.")
    
    user.hashed_password = get_password_hash(req.new_password)
    user.verification_code = None
    user.failed_login_attempts = 0
    db.commit()
    
    access_token = create_access_token(subject=user.email)
    return {"access_token": access_token, "token_type": "bearer"}

# 5. DEVICE SYNCHRONIZATION AND CUSTOM RULES
@app.get("/devices/sync/{device_id}", response_model=List[SortingRule])
def sync_rules(device_id: str, db: Session = Depends(get_db)):
    """The local Python agent polls this endpoint to fetch Organization Rules."""
    # First, update the device's online status
    device = db.get(Device, device_id)
    if not device:
        # Register a new device if unseen
        device = Device(id=device_id, name=f"PC-{device_id[:4]}", user_id=1) 
        db.add(device)
    
    device.is_online = True
    device.last_sync = datetime.utcnow()
    db.commit()
    
    # Return all active sorting rules assigned to this device
    rules = db.exec(select(SortingRule).where(SortingRule.device_id == device_id)).all()
    return rules

class LogReportRequest(BaseModel):
    device_id: str
    folder: str
    logs: List[Dict[str, Any]]

def send_report_email_task(to_email: str, device_id: str, folder: str, logs: List[Dict[str, Any]]):
    if not settings.SMTP_USER or not settings.SMTP_PASSWORD:
        return
        
    now = datetime.now()
    date_str = now.strftime("%d-%m-%Y")
    subject = f"Log day {date_str}"
    
    template = templates.get_template("email_report.html")
    html_content = template.render({"device_id": device_id, "folder": folder, "logs": logs})
    
    try:
        msg = EmailMessage()
        msg['Subject'] = subject
        msg['From'] = settings.SMTP_USER
        msg['To'] = to_email
        msg.set_content("Please activate HTML view to see this organization report.")
        msg.add_alternative(html_content, subtype='html')

        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls()
        server.login(settings.SMTP_USER, settings.SMTP_PASSWORD)
        server.send_message(msg)
        server.quit()
        logger.info(f"Daily report sent to {to_email}")
    except Exception as e:
        logger.error(f"Error sending daily report to {to_email}: {e}")

@app.post("/devices/log/report")
def receive_log_report(req_data: LogReportRequest, request: Request, background_tasks: BackgroundTasks, db: Session = Depends(get_db)):
    auth_header = request.headers.get("Authorization")
    if not auth_header or not auth_header.startswith("Bearer "):
        raise HTTPException(status_code=401, detail="Unauthorized")
    
    token = auth_header.split(" ")[1]
    try:
        payload = jwt.decode(token, settings.SECRET_KEY, algorithms=[settings.ALGORITHM])
        email = payload.get("sub")
    except JWTError:
        raise HTTPException(status_code=401, detail="Invalid token")
        
    user = db.exec(select(User).where(User.email == email)).first()
    if not user:
        raise HTTPException(status_code=401, detail="User not found")

    background_tasks.add_task(send_report_email_task, user.email, req_data.device_id, req_data.folder, req_data.logs)
        
    return {"status": "success", "message": f"Report sent to {user.email}"}

# 6. WEBSOCKET: LIVE EVENT INGESTION
@app.websocket("/ws/events/{device_id}")
async def agent_socket(websocket: WebSocket, device_id: str, db: Session = Depends(get_db)):
    await manager.connect(device_id, websocket)
    try:
        while True:
            # Receive Real-Time JSON movement events from the local agent
            data = await websocket.receive_text()
            event_json = json.loads(data)
            
            # Persist event into the SQLite history log
            new_event = FileEvent(
                device_id=device_id,
                filename=event_json.get("filename"),
                source_path=event_json.get("source_path"),
                dest_path=event_json.get("dest_path"),
                timestamp=datetime.utcnow()
            )
            
            with Session(engine) as session:
                session.add(new_event)
                session.commit()

            # Broadcast to all connected web dashboard clients
            category = new_event.dest_path.replace("\\", "/").rstrip("/").split("/")[-1] if new_event.dest_path else "Other"
            await manager.broadcast_to_dashboard({
                "type": "file_event",
                "category": category,
                "filename": new_event.filename,
                "device_id": device_id,
                "timestamp": new_event.timestamp.isoformat() if new_event.timestamp else None,
            })

    except WebSocketDisconnect:
        manager.disconnect(device_id)
    except Exception as e:
        manager.disconnect(device_id)

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)