import os
import ast
from pathlib import Path

bilingual_summaries = {
    "CONTRIBUTING.md": {
        "en": "Guidelines for contributing to the repository standardizing styling and Pull Requests.",
        "es": "Guía de participación en el repositorio con un estándar de diseño y Pull Requests."
    },
    "LICENSE": {
        "en": "Standard licensing agreement bounding the usage and modification of the software.",
        "es": "Acuerdo de licencia estándar que establece el uso y modificación del software."
    },
    "README.md": {
        "en": "Main project documentation homepage containing setup instructions, architectures, and features.",
        "es": "Página principal de documentación del proyecto. Contiene configuraciones, diseño y características."
    },
    "assets/logo.png": {
         "en": "Vectorized logo application shortcut icon image.",
         "es": "Imagen del icono de la aplicación vectorizado."
    },
    "docker-compose.yml": {
        "en": "Docker orchestration script defining container deployments like the PostgreSQL database.",
        "es": "Script organizador de Docker que define los contenedores de base de datos como PostgreSQL."
    },
    "docs/main.html": {
        "en": "Static HTML output generated by pdoc for standard documentation.",
        "es": "Salida HTML estática autogenerada por pdoc de forma estándar."
    },
    "docs/main_enterprise.html": {
        "en": "Static HTML generated by pdoc focused on the main enterprise frontend module.",
        "es": "Salida de HTML autogenerada por pdoc del submódulo central del escritorio."
    },
    "landing/index.html": {
        "en": "Static landing page frontend template showcasing the product.",
        "es": "Plantilla promocional de landing page que describe el producto."
    },
    "preguntas.md": {
        "en": "Q&A and frequently asked questions doc concerning the project constraints.",
        "es": "Documento de Preguntas Frecuentes sobre las limitaciones del proyecto."
    },
    "scripts/generate_docs.py": {
        "en": "Automation script to build documentation via pdoc library mapping core python modules.",
        "es": "Script para crear documentación automatizada mediante pdoc sobre los modulos centrales."
    },
    "setup_and_run.py": {
       "en": "System Orchestrator tool. Runs subprocesses for launching backend servers, GUI clients, and Docker containers simultaneously.",
       "es": "Herramienta organizadora del Sistema. Ejecuta subprocesos para levantar el servidor backend, el cliente y la base de datos simultáneamente."
    },
    "src/agent/docs/help_en.html": {
        "en": "Embedded HTML user guide used natively within the CustomTkinter desktop interface via TkinterWeb.",
        "es": "Guia de ayuda HTML incrustada en la interfaz grafica desarrollada empleando TkinterWeb."
    },
    "src/agent/file_manager_enterprise.py": {
        "en": "Core local sorting logic and filesystem IO observing directories and parsing extensions asynchronously. Connects securely with server updates.",
        "es": "Manejo central de E/S y organizador de archivos locales, monitorizando extensiones de red asíncrona."
    },
    "src/agent/main_enterprise.py": {
        "en": "Main application layout defining the UI grid orchestration leveraging CustomTkinter elements and handling dynamic multi-threading rendering.",
        "es": "Marco principal de la aplicación definiendo la estructura visual de la UI usando CustomTkinter y multiprocesos simultáneos."
    },
    "src/agent/models/state.py": {
       "en": "Data structures preserving the App authorization state between module refreshes.",
       "es": "Archivo que define e inicializa el App State como estado de almacenamiento en módulos."
    },
    "src/agent/models/theme.py": {
        "en": "Color palette definitions matching modern aesthetic and standard UI guidelines.",
        "es": "Gama de colores, la vista sigue las normas estéticas y plantillas oficiales UI."
    },
    "src/agent/services/api_client.py": {
         "en": "HTTP wrapper communicating securely via Tokenized Bearer JWT headers containing payloads for syncing local telemetry with the DB remote node.",
         "es": "Envoltorio para HTTP conectando a la base de datos con Tokens seguros."
    },
    "src/agent/services/offline_queue.py": {
        "en": "Resilience pattern queuing file transfers temporarily during disconnects caching into a local sqlite mini db buffer.",
        "es": "Buffer local SQLite persistiendo transferencias interrumpidas bajo resiliencia sin conexión."
    },
    "src/agent/views/auth_view.py": {
        "en": "Frontend credentials login logic communicating strictly with the auth handler in main node.",
        "es": "Lógica Frontend de Inicio de sesión de credenciales del nodo central."
    },
    "src/agent/views/dashboard_view.py": {
        "en": "Frontend analytics rendering page loading graphical visualizations using local parsed telemetry variables.",
        "es": "Pagina de analítica y gráficas en Fronend de variables telemétricas locales integradas."
    },
    "src/agent/views/home_view.py": {
        "en": "Interactive layout allowing drop zones for organizing folder systems manually via CustomTkinter drag capabilities.",
        "es": "Lógica interactiva admitiendo zonas de almacenamiento en CustomTkinter utilizando su propiedad Dropper."
    },
    "src/agent/views/rules_view.py": {
         "en": "Interface binding configurations controlling global file sorting behavior with customizable rules matrix.",
         "es": "Propiedades ajustando un panel controlador ajustando normas matriciales manuales configurables."
    },
    "src/backend/api/deps.py": {
        "en": "Dependency wrappers simplifying route injections for generic DB transactions logic on FastAPI.",
        "es": "Simplificando métodos y modelos en las dependencias FastAPI relativas con BDD e inyecciones."
    },
    "src/backend/api/v1/devices.py": {
         "en": "Device endpoint tracking connectivity statuses over the nodes API REST mappings for hardware clients.",
         "es": "Dispositivo para conectividades bajo REST registrando al hardware."
    },
    "src/backend/api/v1/stats.py": {
          "en": "Data aggregator generating time-series statistics directly querying postgres schemas for live frontend dashboards.",
          "es": "Estudios generados en base al BDD por medio de estadísticas métricas para Dashboard Frontend dinámico."
    },
    "src/backend/api/v1/websocket.py": {
         "en": "Asynchronous event-driven sockets pipeline providing bidirection connection channels between Python Clients and analytical frontends in UI rendering.",
         "es": "Canales bidireccionales y métodos en segundo plano asíncronos en Frontend y APIs."
    },
    "src/backend/core/config.py": {
          "en": "Pydantic validator wrapping around env variables verifying mandatory parameters are compliant with system security defaults.",
          "es": "Variables env validadores empleando un Pydantic validando a las estructuras según seguridad predeterminada."
    },
    "src/backend/core/security.py": {
           "en": "Cryptographic engine executing password verifications with Bcrypt handling generic JWT generation routines spanning access layers across domains.",
           "es": "Mecanismo criptográfico usando JWT autogenerativo cruzado e implícito protegiendo información en redes."
    },
    "src/backend/main.py": {
            "en": "FastAPI primary Node Entrypoint bootstrapping background threads, Jinja Templating handlers, Websocket global handlers, routing controllers and dependencies.",
            "es": "Nodo y Entrypoint de la aplicación bajo FastAPI instanciando subprocesos de WebSocket e hilos y jinja templates."
    },
    "src/backend/models/schema.py": {
        "en": "Explicit SQLModels specifying strict typed schemas mirroring real relational entities mapped seamlessly utilizing sqlalchemy behind fastAPI abstractions over engines mapped efficiently.",
        "es": "Implementación explicita e infalible orientada a la manipulación en esquemas estructurados de los sistemas de variables a SQLAlchemy."
    },
     "src/backend/models.py": {
        "en": "General module pointing into logic mapping DB schema definitions.",
        "es": "Reducción sobre la logica a nivel base definiendo el BBDD."
    },
    "src/backend/static/index.html": {
       "en": "Static rendering template associated dynamically via views within the web architecture routing system connected over WebSockets automatically fetching stats to paint dashboards properly.",
       "es": "Ruta y render en HTML para estática de la arquitectura asociada, recolectando las estadísticas asociadas Websocket en vista dinámica."
    },
     "src/backend/templates/email_report.html": {
        "en": "Interactive embedded templating handling HTML dynamic properties interpolating Python arguments directly sending analytical updates via email SMTP systems.",
        "es": "HTML para envíos SMPT vía Email dinámicos con argumentos desde Python en tiempo real logrando reportes de organización."
    },
    "src/backend/templates/email_verification.html": {
         "en": "Templating syntax representing auth recovery sequences embedded efficiently through simple logic loops delivering security PIN configurations quickly replacing old text variations securely.",
         "es": "Estructura generadora representando PIN de recuperación de credenciales y autorización para reemplazar con credibilidad segura."
    },
    "tests/conftest.py": {
         "en": "Initialization hook injecting automated mock contexts simulating SQLite ephemeral environments replacing standard production instances safely prior performing isolated HTTP request mocks properly validating flows natively globally.",
         "es": "Conector automático autogenerado reemplazando esquemas SQLite efímeros produciendo solicitudes para validar módulos al ejecutar pytest."
    },
    "tests/test_auth.py": {
        "en": "Scripting orchestrator evaluating sequentially validation behaviors under simulated payload variants catching exception branches asserting status headers predictably achieving adequate coverage correctly isolating DB leaks during the checks locally.",
        "es": "Autenticación a probar simulado, para captar fallos garantizando cobertura esperable durante el control a BDD."
    },
    "wiki/developer_docs.md": {
        "en": "General overview documentation regarding development instructions.",
        "es": "Consideraciones sobre métodos, instalación, despliego e información técnica aplicable."
    },
    "wiki/devlog.md": {
        "en": "Linear sequential chronological notes mapping all commits or adjustments throughout the history.",
        "es": "Registros de notas ordenadas mapeando todos los commits desde los orígenes de desarrollo de sistema."
    }
}

def analyze_ast(filepath):
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()
            tree = ast.parse(content, filename=filepath)
    except Exception:
        return ""

    classes = [n for n in tree.body if isinstance(n, ast.ClassDef)]
    funcs = [n for n in tree.body if isinstance(n, ast.FunctionDef)]
    
    res = ""
    if classes or funcs:
        res += "\n### 🐍 Python Definitions / Definiciones\n"
        for c in classes:
            res += f"- **{c.name}** (Class / Clase)\n"
        for f in funcs:
            res += f"- **{f.name}** (Function / Función)\n"
    return res

def main():
    base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    docs_output_dir = os.path.join(base_dir, "documentacion_md")
    
    if not os.path.exists(docs_output_dir):
        os.makedirs(docs_output_dir)

    all_files = []
    for root, dirs, files in os.walk(base_dir):
        dirs[:] = [d for d in dirs if d not in [".git", "__pycache__", "venv", "env", "node_modules", "documentacion_md"]]
        for f in files:
            all_files.append(os.path.join(root, f))
            
    for f in all_files:
        if f.endswith('.pyc') or f.endswith('.db') or f.endswith('.png') or f == os.path.abspath(__file__):
             continue
             
        # Normalize the path internally using single slashes for dictionary matching
        rel_path = os.path.relpath(f, base_dir).replace("\\", "/")
        
        # Build document content
        en_desc = "No specific description available."
        es_desc = "No hay descripción específica disponible."
        
        for k, summaries in bilingual_summaries.items():
            if k in rel_path:
                en_desc = summaries["en"]
                es_desc = summaries["es"]
                break
                
        ast_info = ""
        if f.endswith('.py'):
            ast_info = analyze_ast(f)
            
        md_content = f"""# {os.path.basename(f)}

**Path / Ruta**: `{rel_path}`

## 🇬🇧 English
**Description**: {en_desc}

## 🇪🇸 Español
**Descripción**: {es_desc}
{ast_info}
"""
        
        # Determine output path
        out_rel_path = rel_path + ".md"
        # We can write with native slash structure (Windows handles forward and back slashes gracefully)
        out_path = os.path.join(docs_output_dir, out_rel_path)
        
        out_dir = os.path.dirname(out_path)
        if not os.path.exists(out_dir):
            os.makedirs(out_dir)
            
        with open(out_path, 'w', encoding='utf-8') as out_f:
            out_f.write(md_content)
            
    print(f"Bilingual documentation successfully generated in {docs_output_dir} !")

if __name__ == '__main__':
    main()
